version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      androidx:
        patterns:
          - "androidx.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
      google:
        patterns:
          - "com.google.*"
          - "com.android.tools.*"
      square:
        patterns:
          - "com.squareup.*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
